spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dealership_inventory
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
